### ISSUE TITLE
USB storage (PYBFLASH) is very unstable

### ISSUE THREAD

**Issue by Conplug** [OpenNuvoton/NuMicroPy#2]
![1590459809843](https://user-images.githubusercontent.com/43597503/82854535-49e73f00-9f3b-11ea-84ce-e2bcddca5559.jpg)

It's very easy to see the error.

**Comment by chchen59** [comment]
Hi,
Please provide more information about this issue. 
For example: board? firmware version/date?

**Comment by Conplug** [comment]
IOT-M487 V1.3
Firmware:2020/5/7

**Comment by ZaleYu** [comment]
hi Conplug:
Please tell us the Windows version and what kind of USB port you were using?
Did you use a USB hub or directly plug it with your PC?

**Comment by danchouzhou** [comment]
Same thing happen to me.
FW: MicroPython afde8a4-dirty on 2020-05-26; NuMaker-IOT-M487 with Nuvoton-M48x
WIN10 PRO 1909

I think is not the electrical characteristics or the compatibility issues. It's easily broken after writing files into mass storage or interrupt.

**Comment by danchouzhou** [comment]
Please try the script as below.

from pyb import Pin

def sw2_callback(pin):
\t print(pin)

sw2 = Pin.board.SW2
sw2.irq(handler=sw2_callback, trigger=Pin.IRQ_RISING)

**Comment by Conplug** [comment]
> 
> 
> hi Conplug:
> Please tell us the Windows version and what kind of USB port you were using?
> Did you use a USB hub or directly plug it with your PC?

Windows 10 Version:1803
It's the same by using USB hub or directly plugging.

**Comment by chchen59** [comment]
> Please try the script as below.
> 
> from pyb import Pin
> 
> def sw2_callback(pin):
> \t print(pin)
> 
> sw2 = Pin.board.SW2
> sw2.irq(handler=sw2_callback, trigger=Pin.IRQ_RISING)
Yes, I can reproduce it!
It is easy to trigger system hard fault if using print()  in interrupt callback.
I will fix it

**Comment by danchouzhou** [comment]
Hello, 
Also need a try for mass storage device, please. Thank you.

**Comment by Conplug** [comment]
I changed another computer, but the error is the same.

![圖片](https://user-images.githubusercontent.com/43597503/83109864-b8233180-a0f4-11ea-8525-ba0e391c9a86.png)

![圖片](https://user-images.githubusercontent.com/43597503/83109806-9a55cc80-a0f4-11ea-919e-4079dc509c4f.png)

**Comment by chchen59** [comment]
Hi Conplug,
It seems failed on USB enumeration stage. 
Do you have any python code in your main.py?

**Comment by Conplug** [comment]
> 
> 
> Hi Conplug,
> It seems failed on USB enumeration stage.
> Do you have any python code in your main.py?
Yes, but M487 could work with the code yesterday, failed today.

**Comment by chchen59** [comment]
Could you paste your python code?

**Comment by ZaleYu** [comment]
Hi Conplug:
We are not detectives. Please provide more information for debugging. Thank you!

**Comment by Conplug** [comment]
Fixed in the firmware (Jun 4, 2020)
