### ISSUE TITLE
Not working if no USB host.

### ISSUE THREAD

**Issue by danchouzhou** [OpenNuvoton/NuMicroPy#3]
Hello, 
Latest FW.
I just found that if we plug the USB into a phone charger or give it a 3.3V supply directly, won't work. Probably waiting USBD_IS_ATTACHED().

**Comment by danchouzhou** [comment]
Or, not working if USBD is not attached.

**Comment by chchen59** [comment]
Hi, 
Please try the latest firmware(06/04 17:07).

**Comment by chchen59** [comment]
Hi,
If your board is NuMaker-PFM-M487, please also remove L11 and L12.

![image](https://user-images.githubusercontent.com/47237277/83849886-aec44580-a742-11ea-8550-992ca3840ccc.png)

**Comment by danchouzhou** [comment]
Hello, 
Latest firmware(06/04 17:07), with NuMaker-IoT-M487. Can't initialize the wifi module.
>>> import network
>>> wlan = network.WLAN()
Traceback (most recent call last):
  File "<stdin>", in <module>
OSError: failed to init ESP8266 module

**Comment by chchen59** [comment]
Hi,
Please download 06/09 firmware to fix wlan initialize failed issue.

**Comment by danchouzhou** [comment]
Hello, 
FW: MicroPython 5cc7dc6-dirty on 2020-06-10; NuMaker-IOT-M487 with Nuvoton-M48x
Tested, works fine! Thanks.
