### ISSUE TITLE
Wireless can't work.

### ISSUE THREAD

**Issue by Conplug** [OpenNuvoton/NuMicroPy#4]
![圖片](https://user-images.githubusercontent.com/43597503/84110728-fce58b80-aa57-11ea-9b47-b0d4d52d00d0.png)

IOT-M487 V1.3
Firmware:2020/6/4

**Comment by chchen59** [comment]
Hi Conplug,
Please download 06/09 firmware to fix wlan initialize failed issue.

**Comment by Conplug** [comment]
Fixed in 06/09 firmware
