### ISSUE TITLE
There is a syntax in array operating

### ISSUE THREAD

**Issue by Conplug** [OpenNuvoton/NuMicroPy#5]
There is a syntax error in array operating

![圖片](https://user-images.githubusercontent.com/43597503/84235983-7600e380-ab29-11ea-8260-b8c990107fe5.png)

**Comment by chchen59** [comment]
Hi, 
I enabled "MICROPY_PY_BUILTINS_SLICE" option and rebuild firmware. Please download "d9ed9e7" commit.
![image](https://user-images.githubusercontent.com/47237277/84245180-3e993380-ab37-11ea-9741-c40292974e44.png)
