### ISSUE TITLE
SPIM_DMM_RUN_CODE

### ISSUE THREAD

**Issue by danchouzhou** [OpenNuvoton/NuMicroPy#6]
Okay, so now the firmware is around 423KB. Is it possible to move the MicroPython into SPI Flash?

**Comment by chchen59** [comment]
Hi
SPIM for MicropPython is available if enable LVGL option.
Without LVGL option:
    -APROM: micropython code
    -SPI Flash: PYFlash disk(4MB)
With LVGL option:
    -APROM: PYFlash disk (128KB) + micropython code
    -SPI Flash: micropython code
